### ISSUE TITLE
hfssExecuteScript not properly executing script

### ISSUE THREAD

**Issue by arwsl** [yuip/hfss-api#5]
For me at least, the call of hfssExecuteScript() doesn't work. I fixed it with additional Quotes `'"'` to add before and after the hfss.exe-path and the .vbs-script-path. I changed l.114 in the hfssExecuteScript.m file:

```
% Create the Command Path.
cmdHFSS = ['"', hfssExePath, '" ', iconStr, ' ', runStr, ' "' ,  ...
           ScriptFile, '"'];
```

Maybe there is the need to include it properly?

**Comment by yuip** [comment]
True. I just checked and had the same problem. Should be now fixed with your solution. Thanks.
